name: Tests
on:
    pull_request:
        branches:
            - main
jobs:
    test_extension:
      name: Test Chrome Extension
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Setup Node
          uses: actions/setup-node@v3
          with:
              node-version: 18
              cache: "yarn"
        - name: Install dependencies
          run: yarn install --frozen-lockfile
          env:
            PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
        - name: Build Chrome extension
          run: yarn chrome:build
        - name: Test Chrome extension
          uses: mujo-code/puppeteer-headful@18.9.0
          env:
            CI: "true"
          with:
            args: yarn e2e:web:extension
